---
output: 
  html_document: 
    fig_height: 7
    fig_width: 12
editor_options: 
  chunk_output_type: console
---

# Gráfico de redes

\ 


```{r, results ='hide', warning=FALSE, message=FALSE}

library(bipartite)

agrupado <-read.table("recapturas agrupadas.txt", sep = "\t", h=T, row.names=1)

```

\ 


#### Definindo as cores para as interações

A definição dessas cores foi feita no excel (*ver arquivo 'cores das interações':*  <https://github.com/vanessavillanovakuhnen/Diet-overlap-and-Spatial-segregation/blob/main/Gr%C3%A1fico%20de%20rede/recapturas%20agrupadas.txt>

```{r}
cores <- c(
  #Aranae:
  "black"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"black"	,	"black"	,	"black"	,	"green"	,	"black"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"red"	,	"green"	,	"red"	,	"red"	,	"red"	,	"red"	,	"green"	,	"red"	,	"green"	,	"red"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,
  
  #Coleoptera:
  "black"	,	"black"	,	"black"	,	"green"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"green"	,	"green"	,	"black"	,	"green"	,	"black"	,	"black"	,	"black"	,	"black"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"green"	,	"red"	,	"red"	,	"green"	,	"red"	,	"red"	,
  
  #Crustacea:
  "black"	,	"black"	,	"black"	,	"black"	,	"green"	,	"black"	,	"green"	,	"green"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"green"	,	"black"	,	"green"	,	"green"	,	"black"	,	"black"	,	"black"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Diptera: Calliphoridae
  "green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Hemiptera: Cicadidae:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Hymenoptera:
  "green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"black"	,	"green"	,	"black"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"red"	,	"red"	,	"red"	,	"red"	,	"green"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,	"red"	,
  
  #Isoptera:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Lepidoptera:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Myriapoda:
  "green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"black"	,	"black"	,	"black"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"black"	,	"black"	,	"black"	,	"green"	,	"black"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Neuroptera:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Orthoptera:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Pseudoscorpiones:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Mammalia:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Reptilia:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Aves:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Vertebratre n.i.:
  "green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Annonaceae:
  "green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Campomanesia sp.:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Cecropia glaziovii:
  "green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"black"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Moraceae:
  "green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Piperaceae:
  "green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Fruit n.i.1:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"red"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Fruit n.i.2:
  "green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"black"	,	"green"	,	"black"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,
  
  #Fruit n.i.3:
  "green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"black"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"black"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green"	,	"green")
  
  
```

\ 


## Plotando o gráfico

Lembrando que os dados das colunas são chamados de higher e os das linhas de lower

As cores dos boxes eu determinei de acordo com a ordem que os indivíduos foram inseridos na tabela de dados

```{r}
Fig.4 <- plotweb(
  # Dados:
  agrupado, # matriz de dados com recursos como linhas e indivíduos como colunas
  method="cca", # tipo de ordenação dos dados para montar a rede (ver mais opções no manual do bipartite)
  
  # Cores:
  col.high=c(rep("black", 26), rep("red", 19)), # pinta os boxes de cima (individuos)
  col.interaction=cores, # muda a cor das interaçõess
  arrow="no", # muda a direção das interações (ver opções no manual do bipartite)
  bor.col.interaction=cores, # deixa as cores da borda igual da linha
  bor.col.high=c(rep("black", 26), rep("red", 19)), # bordas dos boxes
  
  # Legendas: 
  # (NULL mostra legenda inteira, 0 não mostra nada)
  text.rot=90,  # deixa a legenda na vertical
  high.lablength=0, # legenda dos boxes de cima
  low.lablengt= NULL, # legenda dos boxes de baixo
  
  # Altura dos boxes:
  low.y=0.5,
  high.y=1.70
)
```
